fastlane_version "2.28.8"

default_platform :ios

platform :ios do
  #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #
  # before_all do
  #   ensure_git_status_clean
  # end

  lane :beta do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta

    # increment_build_number(build_number: ENV['CI_BUILD_ID'])

    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    gym(scheme: 'Hubbub-beta', export_method: 'development')

    emails = values[:test_email] ? values[:test_email] : ['judytuna@gmail.com'] # You can list more emails here
    groups = values[:test_email] ? nil : ['firebaes'] # You can define groups on the web and reference them here

    crashlytics(api_token: '796081d516e581059e1a154f6bbbd4a3d8b9416a',
             build_secret: '39ead38110a03d9426da50a27078ef63455b74ad3700d8664efaf589a685bd19',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    slack(
      slack_url: ENV['SLACK_URL'],
      channel: "crashlytics",
      message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    )
  end
end
