fastlane_version "2.28.9"

default_platform :ios

platform :ios do
  #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #
  before_all do
    cocoapods
  end

  desc "Deploy new build to Crashlytics Beta and notify our testers"
  lane :beta do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta

    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    gym(scheme: 'Hubbub', export_method: 'development')

    emails = values[:test_email] ? values[:test_email] : ['judytuna@gmail.com'] # You can list more emails here
    groups = values[:test_email] ? nil : ['firebaes'] # You can define groups on the web and reference them here

    crashlytics(
      api_token: ENV["CRASHLYTICS_API_TOKEN"],
      build_secret: ENV["CRASHLYTICS_BUILD_SECRET"],
      emails: emails,
      groups: groups,
      notes: changelog_from_git_commits,
      notifications: true
    ) # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    slack(
      slack_url: ENV['SLACK_URL'],
      channel: "crashlytics",
      message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    )
  end

  desc "Deploy build on travis-ci"
  lane :travis_deploy do |values|

    # 1) Create a keychain

    keychain_name = "certs"
    create_keychain(
      name: keychain_name,
      default_keychain: false,
      timeout: 3600,
      password: SecureRandom.base64,
      unlock: true
    )

    # 2) Import distribution certificate

    import_certificate(
      certificate_path: "certificates/dev.p12",
      certificate_password: ENV["KEY_PASSWORD"],
      keychain_name: keychain_name
    )

    # 3) Download provisioning profile

    sigh(
      development: true,
      username: ENV["FASTLANE_USERNAME"],
      app_identifier: '*',
      force: true # pick up any new devices
    )

    # 4) Increment the build number - in our case, we're using the travis-ci build number

    increment_build_number(
      build_number: ENV["TRAVIS_BUILD_NUMBER"]
    )

    # 5) Build the app

    gym(
      clean: true,
      scheme: "Hubbub",
      export_method: "development"
    )

    # 6) Release to Crashlytics Beta

    crashlytics(
      api_token: ENV["CRASHLYTICS_API_TOKEN"],
      build_secret: ENV["CRASHLYTICS_BUILD_SECRET"],
      groups: 'firebaes', # yes, that's not a typo
      notes: changelog_from_git_commits,
      notifications: true
    )

    slack(
      slack_url: ENV["SLACK_URL"],
      channel: "crashlytics",
      message: "Successfully uploaded beta release (build #{ENV['TRAVIS_BUILD_NUMBER']}) - see it at https://fabric.io/_/beta"
    )
  end
end
